# Generated by Django 5.1.1 on 2025-03-20 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_administracion', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
