# Generated by Django 5.2 on 2025-05-03 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventario', '0001_initial'),
        ('app_ventas', '0002_alter_venta_creado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventadetalle',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_inventario.producto'),
        ),
    ]
