# Generated by Django 5.1.1 on 2025-03-04 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuarios', '0003_usuario_app_eventos_usuario_app_inventario_and_more'),
        ('app_ventas', '0008_alter_ventadetalle_producto_venta_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='empleado',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'Empleado'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_usuarios.usuario'),
        ),
    ]
