# Generated by Django 5.1.1 on 2025-02-28 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_finanzas', '0003_ingreso_tipo_alter_ingreso_venta'),
        ('app_ventas', '0008_alter_ventadetalle_producto_venta_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingreso',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='venta',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ingreso', to='app_ventas.venta'),
            preserve_default=False,
        ),
    ]
