# Generated by Django 5.1.1 on 2025-03-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0002_cliente_rename_estado_mesa_evento_tipo_evento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='documento_identidad',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='estado_reserva',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='notas_adicionales',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='num_personas',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='tipo_evento',
        ),
        migrations.AddField(
            model_name='evento',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmado', 'Confirmado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=20),
        ),
    ]
