# Generated by Django 5.1.1 on 2025-03-05 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuarios', '0003_usuario_app_eventos_usuario_app_inventario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='app_eventos',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='app_inventario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='app_pedidos',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='app_ventas',
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('usuario', models.OneToOneField(limit_choices_to={'rol': 'Administrador'}, on_delete=django.db.models.deletion.CASCADE, to='app_usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_contratacion', models.DateField(blank=True, null=True)),
                ('usuario', models.OneToOneField(limit_choices_to={'rol': 'Empleado'}, on_delete=django.db.models.deletion.CASCADE, to='app_usuarios.usuario')),
            ],
        ),
    ]
