# Generated by Django 5.1.1 on 2025-03-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuarios', '0004_remove_usuario_app_eventos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='nombre_completo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='nombre_completo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
