# Generated by Django 5.2 on 2025-04-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pedidos', '0003_alter_pedidodetalle_costo_unitario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
