# Generated by Django 5.1.1 on 2025-04-05 01:00

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventario', '0001_initial'),
        ('app_reportes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadisticaVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad_vendida', models.PositiveIntegerField(default=0)),
                ('ingreso_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('rotacion_inventario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('dias_sin_venta', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas_reporte', to='app_inventario.producto')),
            ],
            options={
                'verbose_name': 'Estadística de Venta',
                'verbose_name_plural': 'Estadísticas de Ventas',
                'ordering': ['-fecha'],
                'unique_together': {('producto', 'fecha')},
            },
        ),
    ]
