# Generated by Django 5.1.1 on 2025-04-06 03:01

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrediccionNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_generacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo_prediccion', models.CharField(choices=[('venta', 'Oportunidad de Venta'), ('compra', 'Oportunidad de Compra'), ('precio', 'Ajuste de Precio'), ('stock', 'Optimización de Stock')], max_length=20)),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], max_length=10)),
                ('ventas_ultimos_30_dias', models.PositiveIntegerField(default=0)),
                ('ventas_ultimos_90_dias', models.PositiveIntegerField(default=0)),
                ('rotacion_mensual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('margen_actual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('dias_stock_actual', models.PositiveIntegerField(default=0)),
                ('cantidad_recomendada', models.PositiveIntegerField(default=0)),
                ('precio_recomendado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_accion_recomendada', models.DateField()),
                ('inversion_estimada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ganancia_estimada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('roi_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('analisis', models.TextField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicciones_negocio', to='app_inventario.producto')),
            ],
            options={
                'verbose_name': 'Predicción de Negocio',
                'verbose_name_plural': 'Predicciones de Negocio',
                'ordering': ['-fecha_generacion', 'prioridad'],
            },
        ),
        migrations.CreateModel(
            name='HistorialPrediccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evaluacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('precision', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comentarios', models.TextField()),
                ('prediccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='app_predicciones.prediccionnegocio')),
            ],
        ),
        migrations.CreateModel(
            name='PrediccionVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_generacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('periodo_prediccion', models.CharField(choices=[('semanal', 'Próxima Semana'), ('mensual', 'Próximo Mes'), ('trimestral', 'Próximo Trimestre')], max_length=20)),
                ('unidades_estimadas', models.PositiveIntegerField()),
                ('ingresos_estimados', models.DecimalField(decimal_places=2, max_digits=10)),
                ('confianza_prediccion', models.DecimalField(decimal_places=2, help_text='Porcentaje de confianza', max_digits=5)),
                ('factores_considerados', models.TextField(help_text='Factores que influyen en la predicción')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicciones_venta', to='app_inventario.producto')),
            ],
            options={
                'verbose_name': 'Predicción de Venta',
                'verbose_name_plural': 'Predicciones de Venta',
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.CreateModel(
            name='EstadisticaVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('anual', 'Anual')], max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('unidades_vendidas', models.PositiveIntegerField(default=0)),
                ('ingresos_totales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_promedio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('variacion_periodo_anterior', models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de variación respecto al periodo anterior', max_digits=6, null=True)),
                ('tendencia', models.CharField(blank=True, choices=[('crecimiento', 'Crecimiento'), ('estable', 'Estable'), ('decrecimiento', 'Decrecimiento')], max_length=20, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas_venta', to='app_inventario.producto')),
            ],
            options={
                'verbose_name': 'Estadística de Venta',
                'verbose_name_plural': 'Estadísticas de Venta',
                'ordering': ['-fecha_inicio', 'producto'],
                'unique_together': {('producto', 'periodo', 'fecha_inicio')},
            },
        ),
    ]
