# Generated by Django 5.1.1 on 2025-04-05 00:40

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrediccionVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prediccion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_inicio_analisis', models.DateField()),
                ('fecha_fin_analisis', models.DateField()),
                ('ventas_promedio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tendencia', models.CharField(choices=[('alta', 'Alta Demanda'), ('media', 'Demanda Media'), ('baja', 'Baja Demanda'), ('riesgo', 'Riesgo de Sobre-stock')], max_length=20)),
                ('confianza_prediccion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cantidad_sugerida', models.PositiveIntegerField()),
                ('observaciones', models.TextField(blank=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicciones', to='app_inventario.producto')),
            ],
            options={
                'ordering': ['-fecha_prediccion'],
            },
        ),
        migrations.CreateModel(
            name='EstadisticaVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad_vendida', models.PositiveIntegerField(default=0)),
                ('ingreso_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('rotacion_inventario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('dias_sin_venta', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas', to='app_inventario.producto')),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('producto', 'fecha')},
            },
        ),
    ]
