# Generated by Django 5.1.1 on 2025-04-06 03:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_predicciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediccionnegocio',
            name='fecha_accion_recomendada',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
