# Generated by Django 5.2 on 2025-04-26 23:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventario', '0001_initial'),
        ('app_predicciones', '0002_alter_prediccionnegocio_fecha_accion_recomendada'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrediccionEstacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_producto', models.CharField(choices=[('cerveza', 'Cerveza'), ('vino', 'Vino'), ('destilados', 'Destilados'), ('licores', 'Licores'), ('otros', 'Otros Alcoholes')], default='otros', max_length=20)),
                ('fecha_generacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('mes_prediccion', models.PositiveIntegerField(help_text='Mes del año (1-12) para el que se realiza la predicción')),
                ('temporada', models.CharField(choices=[('alta', 'Temporada Alta'), ('media', 'Temporada Media'), ('baja', 'Temporada Baja')], max_length=10)),
                ('ventas_promedio_historicas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_promedio_historico', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('variacion_precio_anual', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de variación de precio respecto al año anterior', max_digits=5)),
                ('demanda_estimada', models.PositiveIntegerField(default=0)),
                ('precio_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_recomendado', models.PositiveIntegerField(default=0)),
                ('fecha_optima_compra', models.DateField(blank=True, null=True)),
                ('oportunidad_compra', models.BooleanField(default=False)),
                ('ahorro_potencial', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('margen_esperado', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de margen esperado', max_digits=5)),
                ('factores_estacionales', models.TextField(blank=True)),
                ('recomendacion', models.TextField(blank=True)),
                ('confianza_prediccion', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicciones_estacionales', to='app_inventario.producto')),
            ],
            options={
                'verbose_name': 'Predicción Estacional',
                'verbose_name_plural': 'Predicciones Estacionales',
                'ordering': ['-fecha_generacion'],
                'unique_together': {('producto', 'mes_prediccion', 'fecha_generacion')},
            },
        ),
    ]
