# Generated by Django 5.2 on 2025-04-27 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_predicciones', '0003_prediccionestacional'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prediccionestacional',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='prediccionestacional',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='prediccionventa',
            name='producto',
        ),
        migrations.DeleteModel(
            name='EstadisticaVenta',
        ),
        migrations.DeleteModel(
            name='PrediccionEstacional',
        ),
        migrations.DeleteModel(
            name='PrediccionVenta',
        ),
    ]
